[workspace]
members = ["migration"]

[package]
name = "showroom-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
sea-orm = { version = "1", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1"
argon2 = "0.5"
uuid = { version = "1", features = ["v4"] }
chrono = "0.4"
garde = { version = "0.23", features = ["derive", "email"] }
maud = { version = "0.27", features = ["axum"] }
tokio = { version = "1", features = ["full"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["fs", "set-header"] }
tower-livereload = "0.10"
axum-extra = { version = "0.10", features = ["cookie"] }
jsonwebtoken = "9"
time = "0.3"
dotenvy = "0.15"
prosemirror = "0.5.2"
